### ISSUE TITLE
Dumping heap android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by AndrewJack** [tslamic/Dumpey#3]
When running `./dumpey.sh -p com.example.app -bad heapdumps/` I get the following exception:

Dumping heap android.os.TransactionTooLargeException
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:496)
    at android.app.ActivityManagerProxy.dumpHeap(ActivityManagerNative.java:4594)
    at com.android.commands.am.Am.runDumpHeap(Am.java:1101)
    at com.android.commands.am.Am.onRun(Am.java:322)
    at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
    at com.android.commands.am.Am.main(Am.java:99)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

**Comment by tslamic** [comment]
Hi Andrew,

I'm speculating, but it seems like the heap dump is too large to be put in a temp file on the device/emulator. Hopefully there's a way to skip this step, I'll look into it.

Thanks for the report.
